--- 
# Installation of terraform
- name: Install Terraform
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
     - ./group_vars/main.yml
  roles:
     - ../../roles/tomcat_basic_packages_installation
     - ../../roles/terraform_linux_installation