---
- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install the correct web server for Suse
  import_tasks: suse.yml
  when: ansible_facts['os_family']|lower == 'suse'

